### ISSUE TITLE
Can you provide a Conda installation environment or a Docker environment? Many users, including me, do not have root privileges on the server.

### ISSUE THREAD

**Issue by chaimol** [amvarani/Plant_Annotation_TEs#2]
The dependencies installed by your process are too complicated. It is very difficult for many users to install, especially without root permissions to solve so many dependencies.

**Comment by amvarani** [comment]
Dear @chaimol 
I'm sorry for the late reply. 
We have a undergrad student that are compiling all packages into a single docker environment. 
However it seems that the new EDTA version is dealing with SINEs and LINEs in a similar way.
