### ISSUE TITLE
Trying to generate a complete TE report

### ISSUE THREAD

**Issue by MCampos92** [amvarani/Plant_Annotation_TEs#3]
Hi,
I have a question about the annotation of the TEs.
I've used EDTA pipeline to obtain a superfamilies annotation and I'm trying to refine this into a families report using ProcessRepeats-complete.pl but the output doesn't return subclassification (see atached txt).

[ABR114.fasta.mod.txt](https://github.com/amvarani/Plant_Annotation_TEs/files/13938337/ABR114.fasta.mod.txt)

**Comment by amvarani** [comment]
Hi @MCampos92 
You must run the modified EDTA pipeline provided in this repository to be able to execute ProcessRepeats-complete.pl.
